server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    # 数据源基本配置
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/excel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: miss

    # 配置HikariCP
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: ExpendHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1




# mapper配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL


# 开启SpringBoot 的 debug;让控制台打印自动配置的报告
debug: true
logging:
  pattern:
    console: "%-5level %logger{50} - %msg%n"
  register-shutdown-hook: false
  level:
    root: debug
    com:
      zaxxer:
        hikari:
          HikariConfig: warn
          pool:
            HikariPool: warn
